プロフィール機能の実装
sidemt/gulliver_works_profile pull request #1
Opened 2021-03-30 22:25 UTC by sidemt

Generated by Coadmap

2021-04-05 03:44 UTC, uchidataku requested changes
分からない点や初めてやることも多かったと思いますが、ご自分で調べて、よく書けていると思いました。

一番修正が必要なところはAssociationの部分かと思います。
あと、難しいのはcancancanの仕様理解だと思うので、その都度聞いてください。

2021-04-05 03:44 UTC, uchidataku commented on app/controllers/enterprise/v1/employee_profile_controller.rb
> +        authorize! :manage, @employee_profile
もしつけるとしたら、`authorize! :create`が適当かもですね

2021-04-05 03:44 UTC, uchidataku commented on app/controllers/enterprise/v1/employee_profile_controller.rb
> +      before_action :load_and_authorize_employee_profile, only: %i[show update]
`load_and_authorize_resources`を使わず、before_actionを使っているのって何か意図ありますでしょうか？？

2021-04-05 03:44 UTC, uchidataku commented on app/controllers/v1/account_profile_controller.rb
> +    before_action :load_and_authorize_account_profile, only: %i[show update]
employee_profiles_controllerと同様です

2021-04-05 03:44 UTC, uchidataku commented on app/controllers/enterprise/v1/employee_profile_controller.rb
> +    class EmployeeProfileController < EnterpriseController
Associationがhas_oneだとしてもControlllerの命名は複数形が正しいです

2021-04-05 03:44 UTC, uchidataku commented on app/controllers/v1/account_profile_controller.rb
> +  class AccountProfileController < ApplicationController
employee_profiles_controllerと同様です

2021-04-05 03:44 UTC, uchidataku commented on app/controllers/v1/account_profile_controller.rb
> +      authorize! :manage, @account_profile
employee_profiles_controllerと同様です

2021-04-05 03:44 UTC, uchidataku commented on app/controllers/enterprise/v1/employee_profile_controller.rb
> +        render json: @employee_profile, status: :ok
status: :okであればデフォルトで設定されているので付けなくても問題はないですね。
明示的にするのは悪くないですが、showアクションに付いていないので統一感が気になりました。

2021-04-05 03:44 UTC, uchidataku commented on app/controllers/v1/account_profile_controller.rb
> +      render json: @account_profile, status: :ok
employee_profiles_controllerと同様です

2021-04-05 03:44 UTC, uchidataku commented on app/models/account.rb
> +  belongs_to :account_profile, optional: true # optional でないとサインアップ時にエラーとなる
Associationの付け方が違うと思います。
正しくは、`Account has_one AccountProfile`になります。

2021-04-05 03:44 UTC, uchidataku commented on app/models/account_profile.rb
> +  has_one :account, dependent: :destroy
Accountモデル同様です。

2021-04-05 03:44 UTC, uchidataku commented on app/models/employee.rb
> +  belongs_to :employee_profile, optional: true
Account同様です。
正しくは`Employee has_one EmployeeProfile`になります。

2021-04-05 03:44 UTC, uchidataku commented on app/models/employee_profile.rb
> +  has_one :employee, dependent: :destroy
同様です。

2021-04-05 03:44 UTC, uchidataku commented on app/models/profile.rb
> +  enum gender: { MALE: 0, FEMALE: 1, OTHER: 2 }
Enumのkeyに設定するのは小文字の方が適切かと思います。
詳しくはEnumの使い方を調べてもらえればと思いますが、Enumのスコープメソッド的に大文字はよろしくないです。

2021-04-05 03:44 UTC, uchidataku commented on config/routes.rb
> +      patch :profile, to: 'account_profile#update'
has_oneであればresourceを使ってシンプルに書けると思います。

2021-04-05 03:44 UTC, uchidataku commented on config/routes.rb
> +        patch :profile, to: 'employee_profile#update'
accountと同様です。

2021-04-05 03:44 UTC, uchidataku commented on db/migrate/20210330194823_create_profiles.rb
> +      t.integer :gender, null: false, comment: '性別'
enumでnull: falseを設定する場合は、大抵defaultを付けておいた方が良いです

2021-04-05 03:44 UTC, uchidataku commented on db/migrate/20210330194823_create_profiles.rb
> +      t.string :biography, null: false, comment: '自己紹介'
Stoplightの方が間違っていたら申し訳ありませんが、全てのattributeにnull: falseをつけることを定義していないと思います。
必須のattributeだけに付けてください。
また、tableにnull: false設定してあるがModelの方にpresenceを付けていないのはロジックが統一されていないので、気になります。

2021-04-05 03:44 UTC, uchidataku commented on db/migrate/20210331123900_add_profile_id_to_account.rb
> +    add_reference :accounts, :account_profile, type: :uuid, foreign_key: { to_table: :profiles }
Modelに書いた通り、Association修正必要有です

2021-04-05 03:44 UTC, uchidataku commented on db/migrate/20210331123938_add_profile_id_to_employee.rb
> +    add_reference :employees, :employee_profile, type: :uuid, foreign_key: { to_table: :profiles }
同様です。

2021-04-05 03:44 UTC, uchidataku commented on spec/factories/account_profiles.rb
> +  end
valueだけが違うものを別名でactoryに書くのはあまり適切ではないですね。
もし違ったversionを準備するならtraitを使うとシンプルに書けるかと思います。

2021-04-05 03:44 UTC, uchidataku commented on spec/factories/employee_profiles.rb
> +  end
同様です。

2021-04-05 03:44 UTC, uchidataku commented on spec/requests/enterprise/v1/employee_profile_request_spec.rb
> +        biography: employee_profile.biography
factoryの内容をそのままリクエストボディにするのであれば、attributes_forを使うとシンプルに書けるのでオススメです。

2021-04-05 03:44 UTC, uchidataku commented on spec/requests/enterprise/v1/employee_profile_request_spec.rb
> +        biography: employee_profile_b.biography
同様です。

2021-04-05 03:44 UTC, uchidataku commented on spec/requests/v1/account_profile_request_spec.rb
> +        biography: account_profile.biography
同様です。

2021-04-05 03:44 UTC, uchidataku commented on spec/requests/v1/account_profile_request_spec.rb
> +        biography: account_profile_b.biography
同様です。

2021-04-05 03:44 UTC, uchidataku commented on spec/requests/enterprise/v1/employee_profile_request_spec.rb
> +  describe 'POST /employees/:employee_id/profile' do
作成と更新のエンドポイント（必要なら取得も）は、正常系のテストだけではなく、異常系のテストもあると良いかと思います！
特に、自分以外のアカウントがリスエストした時にちゃんと弾かれるようになっているかはチェックしておいた方が良いかと思います。

2021-04-05 03:44 UTC, uchidataku commented on spec/requests/enterprise/v1/employee_profile_request_spec.rb
> +  describe 'PATCH /employees/:employee_id/profile' do
作成エンドポイント同様、異常系テストが欲しいです。

2021-04-05 03:44 UTC, uchidataku commented on spec/requests/v1/account_profile_request_spec.rb
> +  describe 'POST /v1/accounts/:account_id/profile' do
同様です。

2021-04-05 03:44 UTC, uchidataku commented on spec/requests/v1/account_profile_request_spec.rb
> +  describe 'PATCH /v1/accounts/:account_id/profile' do
同様です。

2021-04-06 05:14 UTC, sidemt commented on app/controllers/enterprise/v1/employee_profile_controller.rb
> +      before_action :load_and_authorize_employee_profile, only: %i[show update]
`/employees/{employee_id}/profile` で渡されるのがEmployeeProfile のIDではなくEmployeeのIDなので、 `load_and_authorize_resource` では取得できないのかなと思いました。

https://github.com/CanCanCommunity/cancancan#32-loaders
cancancanを使うのは初めてなのですが、こちらを参照して、Controller名と同じ名前のインスタンス変数に、 `params[:id]` から見つけたレコードを入れてくれるメソッドと理解しました。

2021-04-06 05:30 UTC, sidemt commented on app/controllers/enterprise/v1/employee_profile_controller.rb
> +        render json: @employee_profile, status: :ok
デフォルトで設定されるのは気づいてませんでした…！（単純にshowに付け忘れ）修正します！

2021-04-06 05:46 UTC, sidemt commented on db/migrate/20210331123900_add_profile_id_to_account.rb
> +    add_reference :accounts, :account_profile, type: :uuid, foreign_key: { to_table: :profiles }
こちらなのですが、 has_one と belongs_to を逆にした場合の migration の reference の指定方法が分かりません 😢

`belongs_to` の方に foreign_key を持たせると思っているのですが、
`profiles` というテーブルをSTIで AccountProfile モデルにも EmployeeProfile モデルにも使うとすると、profiles を作成するときのmigrationファイルで

```
    create_table :profiles, id: :uuid do |t|
      t.string :type
      t.references :テーブル名
      ...
    end
```
のように書くと思うのですが、
`t.references :テーブル名` とする時のテーブル名がtypeによって違うと思うので、どう書いたら良いかわからず…。

2021-04-06 05:51 UTC, sidemt commented on app/models/profile.rb
> +  enum gender: { MALE: 0, FEMALE: 1, OTHER: 2 }
こちら、修正します！
Stoplightの仕様書が大文字だったので大文字にした部分でした…仕様書の方ご確認お願いします 🙇 

![gender_enum](https://user-images.githubusercontent.com/25644062/113664855-7507f680-96e7-11eb-88f4-c3b08eac0302.png)

2021-04-06 05:59 UTC, sidemt commented on db/migrate/20210330194823_create_profiles.rb
> +      t.string :biography, null: false, comment: '自己紹介'
こちら、Stoplightでは全て必須になっているかと思います。見るところが間違っていたら申し訳ございません 🙇 
ご確認よろしくお願いいたします。

![profile_required_fields](https://user-images.githubusercontent.com/25644062/113665512-8e5d7280-96e8-11eb-8b43-8e0bc7fab957.png)

2021-04-06 06:03 UTC, sidemt commented on spec/factories/account_profiles.rb
> +  end
trait、知らなかったです！修正します。

2021-04-06 06:18 UTC, sidemt commented on spec/requests/enterprise/v1/employee_profile_request_spec.rb
> +        biography: employee_profile.biography
attributes_for も知らなかったです。知らないと探すのも思いつかないので勉強になります 🙇 修正します！

2021-04-06 06:30 UTC, sidemt commented on spec/requests/enterprise/v1/employee_profile_request_spec.rb
> +  describe 'POST /employees/:employee_id/profile' do
追加します！

2021-04-06 06:33 UTC, sidemt commented on app/controllers/enterprise/v1/employee_profile_controller.rb
> +    class EmployeeProfileController < EnterpriseController
修正しました！

2021-04-06 06:43 UTC, sidemt commented
@uchidataku 
レビューありがとうございます！
異常系のテストの追加がまだなのですが、他、対応可能なところはコメントに従って修正しました。

以下、質問とStoplightの方ご確認いただきたいところをコメントしましたので、ご確認いただければと思います。

質問
・load_and_authorize_resources の使い方
・has_one と belongs_to を逆にする場合の migration の書き方

Stoplightの仕様書の確認依頼
・gender の enum の大文字/小文字（コードは小文字に修正済み）
・すべてのattributeがrequiredになっている

異常系のテストも後ほど追加してpushします。

2021-04-07 05:00 UTC, sidemt commented on spec/requests/enterprise/v1/employee_profile_request_spec.rb
> +  describe 'PATCH /employees/:employee_id/profile' do
追加しました！

2021-04-07 05:00 UTC, sidemt commented on spec/requests/enterprise/v1/employee_profile_request_spec.rb
> +  describe 'POST /employees/:employee_id/profile' do
追加しました！

2021-04-07 05:09 UTC, sidemt commented on app/controllers/enterprise/v1/employee_profile_controller.rb
> +      before_action :load_and_authorize_employee_profile, only: %i[show update]
こちら、自己解決しました。

nestされたリソースに対する書き方
https://github.com/CanCanCommunity/cancancan/blob/develop/docs/Authorizing-controller-actions.md#choosing-actions-on-nested-resources

から色々辿っていって見つけました。 🙇

2021-04-07 05:10 UTC, sidemt commented on app/controllers/v1/account_profile_controller.rb
> +    before_action :load_and_authorize_account_profile, only: %i[show update]
load_and_authorize_resources を使うよう修正しました。

2021-04-07 05:10 UTC, sidemt commented on app/controllers/v1/account_profile_controller.rb
> +      authorize! :manage, @account_profile
load_and_authorize_resources を使うよう修正しました。

2021-04-07 05:10 UTC, sidemt commented on app/controllers/enterprise/v1/employee_profile_controller.rb
> +        authorize! :manage, @employee_profile
load_and_authorize_resources を使うよう修正しました。

2021-04-07 06:23 UTC, uchidataku requested changes
migrationの書き方コメントさせていただきました。

ちなみに、テストってALLグリーンになっていますか？？
Associationがうまく出来てからテストしてもらって、お手数ですが、ALLグリーンになっている画面のスクショを貼ってもらいたいです。
よろしくお願いします。

2021-04-07 06:23 UTC, uchidataku commented on db/migrate/20210331123900_add_profile_id_to_account.rb
> +    add_reference :accounts, :account_profile, type: :uuid, foreign_key: { to_table: :profiles }
Profileのtableのmigrationでそのまま
`t.references :account, index: true, foreign_key: true, type: :uuid`と`t.references :employee, index: true, foreign_key: true, type: :uuid`を指定してしまって問題ないです
Modelの方で、belongs_toのところにoptionalをつけてもらえれば、nullだとしても問題なくいけます。
例えばTypeがAccountの場合、account_idに値が入り、employee_idはnullというレコードになるということです。

2021-04-07 06:23 UTC, uchidataku commented on db/migrate/20210330194823_create_profiles.rb
> +      t.string :biography, null: false, comment: '自己紹介'
失礼しました。
こちらのミスです。
OpenAPIの方を修正対応しておきます。

2021-04-07 07:49 UTC, sidemt commented on db/migrate/20210330194823_create_profiles.rb
> +      t.integer :gender, null: false, comment: '性別'
こちら、Stoplightの仕様書上はどの値をdefaultにするかの指定は無いようですが、`male` `female` `other` のどれでも大丈夫でしょうか？

また、仕様書上の例が `MALE` `FEMALE` `OTHER` と大文字になっているので、こちらも必要であれば仕様書の修正よろしくお願いいたします。 :bow:

2021-04-07 09:26 UTC, sidemt commented on db/migrate/20210330194823_create_profiles.rb
> +      t.string :biography, null: false, comment: '自己紹介'
>tableにnull: false設定してあるがModelの方にpresenceを付けていない

こちら、AccountProfile, EmployeeProfile の継承元となる `Profile` モデルで `presence: true` のvalidation を設けているのですが、それで大丈夫でしょうか？私の手元で動作を確認した限り、 validation は効いているようです。

2021-04-07 09:27 UTC, sidemt commented on db/migrate/20210331123900_add_profile_id_to_account.rb
> +    add_reference :accounts, :account_profile, type: :uuid, foreign_key: { to_table: :profiles }
両方付ければ良かったのですね！その発想が無かったです… 💦 ありがとうございます！それでうまくいきました。

2021-04-07 09:31 UTC, sidemt commented
Association修正しました！テスト結果のスクリーンショット添付します。よろしくお願いいたします。

![test_results](https://user-images.githubusercontent.com/25644062/113844382-61d05600-97cf-11eb-81a7-1db1a709e36f.png)

2021-04-07 10:33 UTC, uchidataku approved these changes
enumのdefaultだけ指摘させていただきましたが、テストも含めてよく書けていると思います！
LGTMです！

2021-04-07 10:33 UTC, uchidataku commented on app/models/profile.rb
> +  attribute :gender, :integer, default: 2
細かい話ですが、慣習としてenumのdefaultは最初の0を設定する感じになっているのでそれに従っている方が無難だと思います。
今回、OpenAPIの方にdefalutの記述なかったのですみません。
maleがdefaultにしてもらって構いません。

2021-04-07 10:33 UTC, uchidataku commented on db/migrate/20210330194823_create_profiles.rb
> +      t.integer :gender, null: false, default: 2, comment: '性別'
同様です。

2021-04-07 10:33 UTC, uchidataku commented on db/schema.rb
> +    t.integer "gender", default: 2, null: false, comment: "性別"
同様です。

2021-04-07 11:05 UTC, sidemt commented
レビューありがとうございました！enumのdefaultも修正しました。

2021-04-08 04:22 UTC, merged