職歴機能の実装
sidemt/gulliver_works_profile pull request #2
Opened 2021-04-09 07:21 UTC by sidemt

Generated by Coadmap

2021-04-10 03:00 UTC, uchidataku requested changes
かなり良い感じですね！
数カ所指摘させていただきました。

プロフィールと同様、テストのALLグリーン画面のスクショも頂けると助かります。
よろしくお願いします！

2021-04-10 03:00 UTC, uchidataku commented on config/routes.rb
> +  end
こちら不要だと思うのですが、何か意図はありますでしょうか？？

2021-04-10 03:00 UTC, uchidataku commented on app/models/industry.rb
> +  has_many :work_histories, dependent: :destroy
こちらはdependent: nullifyの方が適切かと思います。

2021-04-10 03:00 UTC, uchidataku commented on app/models/occupation.rb
> +  has_many :work_histories, dependent: :destroy
同様です。

2021-04-10 03:00 UTC, uchidataku commented on app/controllers/v1/work_histories_controller.rb
> +    load_and_authorize_resource :work_history, through: :account, only: [:index, :create]
今回OpenAPIに書いてある通りのURIでエンドポイントを実装していく場合、shallow: trueを使うと簡潔に書けると思うので確認してみてください

2021-04-10 03:00 UTC, uchidataku commented on app/controllers/v1/work_histories_controller.rb
> +    def work_history_params
こちらは指摘というより補足ですが、「モデル名_params」という名称でも問題ないですが、わざわざモデルごとにかき分けるより「resource_params」という名称で書くとcancancanがよしなにやってくれます

2021-04-10 04:24 UTC, sidemt commented on config/routes.rb
> +  end
rails g controller したときの消し忘れですね…ご指摘ありがとうございます！不要なので削除しておきます。

2021-04-10 04:32 UTC, sidemt commented on app/models/industry.rb
> +  has_many :work_histories, dependent: :destroy
たしかに！
もし業種（職種）が削除されたときに、その業種が選択されている職歴まで消えてしまうのはアプリの挙動としておかしいから…ということですよね？

nullify に変更しておきます！

2021-04-10 05:42 UTC, sidemt commented on app/controllers/v1/work_histories_controller.rb
> +    def work_history_params
なるほど！これも知らなかったです。cancancan便利ですね ✨

2021-04-10 06:02 UTC, sidemt commented on app/controllers/v1/work_histories_controller.rb
> +    load_and_authorize_resource :work_history, through: :account, only: [:index, :create]
shallow: true 使って書き換えてみました！こちらのオプションも知らなかったです。ありがとうございます！

2021-04-10 06:04 UTC, sidemt commented
コメントいただいた所を修正してpushしました。
テスト結果添付します。ご確認よろしくお願いいたします！

![テスト結果5808](https://user-images.githubusercontent.com/25644062/114260144-f922ec80-9a0d-11eb-90fc-258308d630eb.png)

2021-04-10 08:43 UTC, uchidataku requested changes
もうほぼ問題ないのですが、routingの部分だけ修正をお願いします！

2021-04-10 08:43 UTC, uchidataku commented on config/routes.rb
> +    resources :work_histories, only: [:show, :update, :destroy]
すみません、もう一点だけ
こちらも同様にshallowオブションをつけることで簡潔に書くことができるので確認してみてください

2021-04-10 08:43 UTC, uchidataku commented on app/models/work_history.rb
> +end
こちらは指摘というより、アプリケーションロジックの話なんですが、
is_employedのbooleanは在職中か離職中のステータスなので、falseの場合はuntil_dateもpresence: trueにする方が望ましいかと思います

2021-04-10 08:43 UTC, uchidataku commented on app/models/work_history.rb
> +end
　ちなみに、もしつける場合は一度specの方でちゃんとvalidationが働くことかどうかチェックすることをオススメします

2021-04-11 06:16 UTC, sidemt commented on config/routes.rb
> +    resources :work_histories, only: [:show, :update, :destroy]
できました！変更しておきます。

2021-04-11 06:36 UTC, sidemt commented on app/models/work_history.rb
> +end
こちら、ご指摘ありがとうございます。確かにそうですね。
逆に、 true の場合は until_date が未入力であることもバリデーションした方がいいでしょうか？

アプリの機能としてどちらにするかという話になるかとは思いますが…
例えば、退職予定日として入力できるようにするなら is_emplyed: true かつ until_date: 入力済み(未来の日付) という状態も許可して良いのかなと。

2021-04-11 07:20 UTC, sidemt commented
下記、対応しました。ご確認よろしくお願いいたします！

- routes を shallow オプションを使って書き換え
- is_employed: falseの場合はuntil_dateもpresence: true であることを確認するバリデーションを追加
- WorkHistory のバリデーションのテストを追加 (spec/models/work_history_spec.rb)

![image](https://user-images.githubusercontent.com/25644062/114295678-afa3d180-9ae1-11eb-8de1-5605b382efb2.png)

2021-04-12 06:10 UTC, uchidataku approved these changes
バッチリですね！
LGTMです！

2021-04-13 03:06 UTC, merged