学歴機能の実装
sidemt/gulliver_works_profile pull request #3
Opened 2021-04-15 07:50 UTC by sidemt

Generated by Coadmap

2021-04-15 08:24 UTC, sidemt commented
テスト結果こちらです。レビューよろしくお願いいたします！

![image](https://user-images.githubusercontent.com/25644062/114838084-50aac900-9e0f-11eb-8c58-f86bf325616c.png)

2021-04-16 01:30 UTC, uchidataku requested changes
もう完璧ですね！
parseするメソッドも自作して、フロントからとても助かると思います！
一箇所だけincludeのところだけ返信お願いします。

2021-04-16 01:30 UTC, uchidataku commented on app/models/academic_history.rb
> +    end
良いですね！

2021-04-16 01:30 UTC, uchidataku commented on db/migrate/20210414033813_create_academic_histories.rb
> +    create_table :academic_histories, id: :uuid do |t|
今までのレビューで完全に漏れてしまっていたんですが、カラムだけじゃなくテーブルにもcommentを付けられるので、次回から付けると良いと思います。

2021-04-16 01:30 UTC, uchidataku commented on app/controllers/v1/academic_histories_controller.rb
> +      render json: @academic_histories, include: [:occupation, :industry]
こちらのincludeを付けている意図って何でしょうか？？

2021-04-16 04:20 UTC, sidemt commented on app/controllers/v1/academic_histories_controller.rb
> +      render json: @academic_histories, include: [:occupation, :industry]
WorkHistoryからコピペした時の消し忘れでした… 😂 ご指摘ありがとうございます！削除しておきます。

2021-04-16 04:25 UTC, sidemt commented on db/migrate/20210414033813_create_academic_histories.rb
> +    create_table :academic_histories, id: :uuid do |t|
こちら、前回までは自分でも気が付いて付けていたので、今回が付け忘れでした！ついでに付けておきます。

マイグレーションにこうやってコメントが付けられることは知らなかったので、今後自分のプロジェクトでも役に立ちそうです 🙏

2021-04-16 04:31 UTC, sidemt commented
対応しました！よろしくお願いいたします。

![image](https://user-images.githubusercontent.com/25644062/114971727-f1ed5a00-9eb7-11eb-96d8-a84ec425dd81.png)

2021-04-16 06:31 UTC, uchidataku approved these changes
LGTMです！
お疲れ様でした！！

2021-04-16 12:06 UTC, merged